apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ikulyk404/busyboxplus:curl
            command: ["sh", "-c", "curl http://todoapp-service.todoapp.svc.cluster.local/api/health"]
            resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "150m"
          # restartPolicy: OnFailure
          
