apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemonset
  namespace: mateapp
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      key: busybox
  template:
    metadata:
      labels:
        key: busybox
    spec:
      containers:
      - name: busybox
        image: ikulyk404/busyboxplus:curl
        command: ["sh", "-c", "while true; do curl http://todoapp-service.todoapp.svc.cluster.local; sleep 5; done"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"